### PR TITLE
Update to Copier template 0.3.7

### PR DESCRIPTION
**Pull request by lkubb**
### What does this PR do?
Updates the Copier template to 0.3.7.

* Fixes the docs build in CI
* Publishes docs to GitHub Pages

### What issues does this PR fix or reference?
Fixes:

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by max-arnold** [comment]
@lkubb I'm on vacation at the moment, will be able to take a look in August

**Comment by lkubb** [comment]
@max-arnold Thanks for the response! No worries, hope you enjoy your vacation. :)

It's just a boilerplate update, but I didn't feel comfortable overriding the branch protection.

**Review by max-arnold — APPROVED** [review]

**Comment by lkubb** [comment]
@max-arnold Thanks for reviewing and sorry for dismissing, opted to update this again to avoid CI failures after a merge with the new workflow permissions.

Maybe you can check out the new commit as well. If you're fine with the changes here, I don't think we'll need separate reviews for similar updates to the other extension repos.

**Review by max-arnold — APPROVED** [review]
LGTM

**Pull request merged**
